name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /root/jira

          # Pull latest changes from GitHub
          git fetch --all
          git reset --hard origin/main

          # Create .env file inside backend/
          cat > backend/.env << 'EOF'
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASS=${{ secrets.DB_PASS }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF

          # Restart containers with new env
          docker-compose down
          docker-compose up -d --build

